name: Build IV Performance Booster

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0, )'

    - name: Build Project
      run: msbuild IVPerformanceBooster.sln /p:Configuration=Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: IVPerformanceBooster-windows-x86
        path: Release/*.asi
